### ISSUE TITLE
Git clone not working command 

### ISSUE THREAD

**Issue by Amolmeh** [jatinkalwar/Master-Bomber#1]
![Screenshot_20210528-013433_Termux](https://user-images.githubusercontent.com/84330667/119890018-ed0ad400-bf54-11eb-90eb-b031c1607184.jpg)

**Comment by jatinkalwar** [comment]
you have to install git first then you can clone any repository
First type pkg install git after the installation type git clone
(repository link) then enter
Thanks to contact us😇
